name: Docker Push via /u/ scope

on:
  push:
    paths:
      - "**.js"
      - "**.json"
      - "Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t ghcr.io/u/dkmattiucll/it-landscape:latest .

      - name: Push image
        run: docker push ghcr.io/u/dkmattiucll/it-landscape:latest
