name: Build and Push Docker Image

on:
  push:
    paths:
      - "**.js"
      - "**.json"
      - "Dockerfile"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run:
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest
